# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(choices=[('SEC', 'Security'), ('CLN', 'Cleaning'), ('MNT', 'Maintenance'), ('ELC', 'Electrical'), ('PLB', 'Plumbing'), ('GRD', 'Gardening'), ('HSK', 'Housekeeping'), ('MID', 'Maid'), ('ADM', 'Administrative'), ('RCP', 'Receptionist'), ('OAS', 'Office Assistant'), ('SUP', 'Supervisor'), ('MGR', 'Manager'), ('ITS', 'IT Support'), ('NET', 'Network Engineer'), ('TEC', 'Technician'), ('DRV', 'Driver'), ('STK', 'Storekeeper'), ('DSP', 'Dispatch'), ('COU', 'Courier'), ('CHF', 'Chef'), ('COK', 'Cook'), ('WTR', 'Waiter'), ('LDR', 'Laundry'), ('CTR', 'Catering'), ('NRS', 'Nurse'), ('FAD', 'First Aid Staff'), ('FSF', 'Fire Safety Officer'), ('WTM', 'Watchman'), ('LTO', 'Lift Operator'), ('ELE', 'Electrician'), ('CAR', 'Carpenter'), ('PNT', 'Painter')], default='SEC', max_length=255, verbose_name='Role')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, max_length=50, verbose_name='Status')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Hired Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society', verbose_name='Society')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Half Day', 'Half Day')], default='Present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked_by', to='staff.staff')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='staff_staff_date_5bf703_idx'), models.Index(fields=['status'], name='staff_staff_status_e16c6c_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
