# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('Employee', 'Employee'), ('Visitor', 'Visitor'), ('Delivery', 'Delivery')], default='Employee', max_length=20)),
                ('visitor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('visitor_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('visitor_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_type', models.CharField(choices=[('IN', 'Check-In'), ('OUT', 'Check-Out')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('gate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inout_records', to='staff.staff')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inout_records', to='society.society')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_entries', to='staff.staff')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entry_type'], name='entry_exit__entry_t_4da8cf_idx'), models.Index(fields=['timestamp'], name='entry_exit__timesta_65dfd2_idx'), models.Index(fields=['person_type'], name='entry_exit__person__c5c949_idx')],
            },
        ),
    ]
