# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('society', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Festival', 'Festival Celebration'), ('Meeting', 'Committee Meeting'), ('Sports', 'Sports / Competition'), ('Cultural', 'Cultural Program'), ('Cleanup', 'Clean-up Drive'), ('Other', 'Other')], default='Other', max_length=30)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('organized_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('is_public', models.BooleanField(default=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to='staff.staff')),
                ('participants', models.ManyToManyField(blank=True, related_name='events_participating', to='authentication.owner')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='society.society')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['category'], name='society_eve_categor_67a4a8_idx'), models.Index(fields=['status'], name='society_eve_status_7177af_idx')],
            },
        ),
    ]
