# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerOrBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('no_of_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Floors')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society', verbose_name='Society')),
            ],
            options={
                'verbose_name': 'TowerOrBlock',
                'verbose_name_plural': 'TowerOrBlocks',
            },
        ),
        migrations.CreateModel(
            name='FloorDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tower_or_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.towerorblock', verbose_name='Tower or Block')),
            ],
            options={
                'verbose_name': 'FloorDescription',
                'verbose_name_plural': 'FloorDescriptions',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(choices=[('ST', 'Studio'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('PH', 'Penthouse'), ('DP', 'Duplex')], max_length=5, verbose_name='Flat Type')),
                ('flat_number', models.CharField(max_length=50, verbose_name='Flat Number')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society', verbose_name='')),
                ('tower_or_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.towerorblock', verbose_name='Tower or Block')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
            },
        ),
    ]
