# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('All', 'All'), ('Owners', 'Owners'), ('Employees', 'Employees')], default='All', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice_attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_notices', to='staff.staff')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='society.society')),
            ],
            options={
                'ordering': ['-posted_on'],
                'indexes': [models.Index(fields=['priority'], name='notice_noti_priorit_b5f11a_idx'), models.Index(fields=['audience'], name='notice_noti_audienc_9f7209_idx')],
            },
        ),
    ]
