# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELC', 'Electrical'), ('PLB', 'Plumbing'), ('HVC', 'HVAC / Air Conditioning'), ('CIV', 'Civil / Structural'), ('GRD', 'Gardening'), ('CLN', 'Cleaning'), ('PNT', 'Painting'), ('HSK', 'Housekeeping'), ('PST', 'Pest Control'), ('LFT', 'Lift / Elevator'), ('FSF', 'Fire Safety'), ('GEN', 'General Maintenance')], default='GEN', max_length=50, verbose_name='Maintenance Category')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('INP', 'In Progress'), ('CMP', 'Completed'), ('HLD', 'On Hold'), ('CNL', 'Cancelled')], default='PND', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='staff.staff')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='authentication.owner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_0773c2_idx'), models.Index(fields=['priority'], name='maintenance_priorit_ec7e12_idx'), models.Index(fields=['created_at'], name='maintenance_created_311a90_idx')],
            },
        ),
    ]
