# Generated by Django 5.2.7 on 2025-10-29 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('society', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance Issue'), ('StaffBehavior', 'Staff Behavior'), ('Cleanliness', 'Cleanliness'), ('Security', 'Security'), ('Noise', 'Noise / Disturbance'), ('Other', 'Other')], default='Other', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Received', 'Received'), ('UnderReview', 'Under Review'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Received', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('raised_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to='staff.staff')),
                ('linked_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_complaints', to='maintenance.maintenancerequest')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_raised', to='authentication.owner')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='society.society')),
            ],
            options={
                'ordering': ['-raised_on'],
                'indexes': [models.Index(fields=['category'], name='complaints__categor_8115a1_idx'), models.Index(fields=['status'], name='complaints__status_7c8de0_idx')],
            },
        ),
    ]
